In [1]:
import numpy as np

In [2]:
from numpy import random

In [3]:
#輸入np array
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [4]:
data.dtype#查詢資料型別

dtype('int32')

In [5]:
#輸入計算出array維度與元素數量
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
print('維度 :', data.ndim)
print('元素數量 :', data.size)

維度 : 1
元素數量 : 10


In [12]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
one = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 9])
two = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
print('data * 2 :', data * 2)#可直接對array進行四則運算
print('乘法算算 :', one * two)#要記得對象若也是array長度要相等
print('連乘 :', data ** 2)#data的2次方
print('除法 :', np.around((one / two), 3))#around強迫四捨五入到小數點後第三位

data * 2 : [18  4  6  8 20 12 14 16  2 10]
乘法算算 : [10 18 24 28 30 30 28 24 18  9]
連乘 : [ 81   4   9  16 100  36  49  64   1  25]
除法 : [0.1   0.222 0.375 0.571 0.833 1.2   1.75  2.667 4.5   9.   ]


In [13]:
#array值排序
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
print('原本的值 :', data)
data.sort()
print('小到大的排序', data)
data[::-1].sort()
print('大到小的排序', data)

原本的值 : [ 9  2  3  4 10  6  7  8  1  5]
小到大的排序 [ 1  2  3  4  5  6  7  8  9 10]
大到小的排序 [10  9  8  7  6  5  4  3  2  1]


In [14]:
#array最小值、最大值、總和、累積和、累積比例
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
print('最小值 :', data.min())
print('最大值 :', data.max())
print('總和 :', data.sum())
print('累積和 :', data.cumsum())
print('累積比例 :', data.cumsum() / data.sum())

最小值 : 1
最大值 : 10
總和 : 55
累積和 : [ 9 11 14 18 28 34 41 49 50 55]
累積比例 : [0.164 0.2   0.255 0.327 0.509 0.618 0.745 0.891 0.909 1.   ]


In [15]:
#產生亂數
random.seed(0)#指定亂數種子
print('均勻分布，0.0以上，小於1.0 :',random.rand(10))#若在括號內給兩個數值m,n則會生成m*n的矩陣
random.seed(0)#指定亂數種子
print('均勻分布，0.0以上，小於1.0(和rand的引數指定方法不同) :',random.random_sample(10))
random.seed(0)#指定亂數種子
print('均勻分布。任意範圍的整數 :',random.randint(1,100))#在1~100生成隨機整數
random.seed(0)#指定亂數種子
print('常態分布。平均為0、標準差為1的亂數 :',random.randn(10))#若在括號內給兩個數值m,n則會生成m*n的矩陣
random.seed(0)#指定亂數種子
print('常態分布。任意平均、標準差的亂數 :',random.normal(loc = 10, scale = 0.1, size = 10))#loc=平均值/scale=標準差/size=大小(亦可設定成矩陣)
#print('二項分布的亂數 :',random.bionomial(10))_還沒研究
#print('betta分布的亂數 :',random.beta(10))_還沒研究
#print('gamma分布的亂數 :',random.gemma(10))_還沒研究
print('卡方分布的亂數 :',random.chisquare(df = 1, size = 10))#df=自由度數/size=大小(亦可設定成矩陣)

均勻分布，0.0以上，小於1.0 : [0.549 0.715 0.603 0.545 0.424 0.646 0.438 0.892 0.964 0.383]
均勻分布，0.0以上，小於1.0(和rand的引數指定方法不同) : [0.549 0.715 0.603 0.545 0.424 0.646 0.438 0.892 0.964 0.383]
均勻分布。任意範圍的整數 : 45
常態分布。平均為0、標準差為1的亂數 : [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]
常態分布。任意平均、標準差的亂數 : [10.176 10.04  10.098 10.224 10.187  9.902 10.095  9.985  9.99  10.041]
卡方分布的亂數 : [1.759e+00 6.570e-01 1.009e-02 8.176e-04 1.643e+00 8.620e+00 4.259e-01
 2.798e-02 4.110e-02 5.457e-01]


In [16]:
#顯示到小數點後第三位
%precision 3

'%.3f'

In [17]:
data = np.array([9,2,3,4,10,6,7,8,1,5])

# 隨機取出
# 取出10個(允許重複，放回抽樣)
print(random.choice(data, 10))
#  取出10個(不允許重複，不放回抽樣)
print(random.choice(data, 10, replace = False))

[ 4  3  8  3  9  9 10  6  6  7]
[ 4  6  9  7  3  8  5  2 10  1]


In [18]:
#產生矩陣
array1 = np.arange(9)
print(array1)
array2 = np.arange(9).reshape(3,3)
print(array2)
print('第一列 :', array2[0,:])
print('第一行 :', array2[:,0])

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
第一列 : [0 1 2]
第一行 : [0 3 6]


In [19]:
#矩陣運算
array1 = np.arange(9).reshape(3,3)
array2 = np.arange(9, 18).reshape(3,3)#arrange(start,end)
print('array1 :', array1)
print('array2 :', array2)
print('矩陣乘法 :', np.dot(array1, array2))
print('元素相乘 :', array1 * array2)#個元素對應位置相乘

array1 : [[0 1 2]
 [3 4 5]
 [6 7 8]]
array2 : [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
矩陣乘法 : [[ 42  45  48]
 [150 162 174]
 [258 279 300]]
元素相乘 : [[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


In [20]:
#製作元素為0或1的矩陣
print(np.zeros((2, 3), dtype = np.int64))
print(np.ones((2, 3), dtype = np.float64))#可定義型態

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
