請輸入Student ID:s1081447

SVM

In [1]:
#import package
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn import ensemble, metrics
from sklearn.metrics import accuracy_score
from sklearn.utils import shuffle
import math

In [2]:
# 開啟 CSV 檔案
dataset= pd.read_csv('train.csv')
testset= pd.read_csv('test.csv')

In [3]:
#將dataset shuffle
dataset = shuffle(dataset)
label = dataset.label
dataset = dataset[dataset.columns[:449]]

In [4]:
#svm
#引入library
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

#10-fold cross-validation
kfold = KFold(10, True)
predicted = []
expected = []

#訓練模型
#會出現warning為正常現象，不用理會，也可以另外寫code去ignore
for train, test in kfold.split(dataset):#kfold.split將dataset拆成train,test
    X_train= dataset.iloc[train]
    Y_train = label.iloc[train]

D:\file\anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass shuffle=True as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [5]:
print("TRAIN:", train, "TEST:", test)

TRAIN: [   0    1    2 ... 1736 1738 1740] TEST: [   6   22   30   44   45   65   75  100  109  113  114  142  151  155
  158  161  169  171  189  202  205  231  236  241  243  264  284  289
  293  306  316  334  365  386  412  419  453  454  455  456  469  472
  476  491  494  513  519  547  548  595  614  616  617  619  633  657
  659  665  670  686  687  703  710  711  713  716  726  737  742  780
  785  787  797  808  820  825  854  855  857  892  903  910  915  918
  919  921  928  930  946  948  950  954  962  976  984  985 1004 1013
 1021 1036 1042 1051 1058 1060 1073 1087 1102 1107 1110 1111 1138 1155
 1163 1191 1208 1232 1246 1251 1261 1266 1276 1311 1326 1332 1368 1370
 1374 1380 1393 1399 1403 1412 1421 1426 1430 1434 1436 1438 1440 1447
 1460 1471 1477 1482 1488 1497 1502 1521 1523 1529 1534 1545 1558 1559
 1570 1574 1582 1587 1602 1608 1609 1610 1632 1638 1641 1642 1647 1674
 1681 1696 1706 1734 1737 1739]


In [6]:
#訓練模型
#會出現warning為正常現象，不用理會，也可以另外寫code去ignore
for train, test in kfold.split(dataset):
    X_test = dataset.iloc[test]
    Y_test = label.iloc[test]
    svm = OneVsRestClassifier(SVC(gamma='scale')).fit(X_train,Y_train)
    expected.extend(Y_test)
    predicted.extend(svm.predict(X_test))

In [7]:
print("Macro-average: {0}".format(metrics.f1_score(expected,predicted,average='macro')))
print("Micro-average: {0}".format(metrics.f1_score(expected,predicted,average='micro')))
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected, predicted))
accuracy = accuracy_score(expected, predicted)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

print("Average = macro")
print('precision:',metrics.precision_score(expected, predicted,average='macro')) 
print('recall:',metrics.recall_score(expected, predicted,average='macro'))
print('F1-score:',metrics.f1_score(expected, predicted,labels=[1,2,3,4],average='macro'))

print("\n")
print("Average = micro")
print('precision:', metrics.precision_score(expected, predicted, average='micro')) 
print('recall:',metrics.recall_score(expected, predicted,average='micro'))
print('F1-score:',metrics.f1_score(expected, predicted,labels=[1,2,3,4],average='micro'))

print("\n")
print("Average = weighted")
print('precision:', metrics.precision_score(expected, predicted, average='weighted'))
print('recall:',metrics.recall_score(expected, predicted,average='weighted'))
print('F1-score:',metrics.f1_score(expected,predicted,labels=[1,2,3,4],average='weighted'))

Macro-average: 0.974595370139569
Micro-average: 0.9753015508328546
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       145
           1       0.96      0.90      0.93       207
           2       1.00      0.97      0.98       119
           3       0.90      0.97      0.94       238
           4       0.97      0.99      0.98       256
           5       1.00      1.00      1.00       264
           6       1.00      0.99      1.00       240
           7       0.99      0.99      0.99       272

    accuracy                           0.98      1741
   macro avg       0.98      0.97      0.97      1741
weighted avg       0.98      0.98      0.98      1741

[[139   0   0   0   6   0   0   0]
 [  0 187   0  20   0   0   0   0]
 [  0   0 115   4   0   0   0   0]
 [  0   6   0 232   0   0   0   0]
 [  0   0   0   0 253   0   0   3]
 [  0   0   0   0   0 264   0   0]
 [  0   1   0   1   0   0 238   0]
 [  0   1   0   0   1   0   0 270]]
A

In [8]:
#從訓練資料隨機抓幾筆出來做測試
from numpy import random

#確認訓練資料的筆數
dataset= pd.read_csv('train.csv')
print('資料的形式:{}'.format(dataset.shape))

#numpy.random.randint(low, high=None, size=None, dtype='l')
#隨機選出10筆
random.seed(1)
index_random=random.randint(1,1740,10)
print(index_random)

#從訓練資料取出這10筆資料
dataset_fortest = dataset.iloc[index_random]
label = dataset_fortest.label
dataset_fortest = dataset_fortest[dataset_fortest.columns[:449]]
dataset_fortest

資料的形式:(1741, 450)
[1062  236 1097  906  716 1670  848  961  145  130]


col1  col2  col3  col4  col5  col6  col7  col8   col9  col10  ...  \
1062  70.1  70.1  70.1  70.0  70.2  70.2  70.4  70.5   70.7   70.8  ...   
236   78.6  78.6  78.6  78.6  79.2  79.9  80.5  81.3   82.2   83.6  ...   
1097  81.4  81.4  81.4  81.5  81.8  82.0  82.3  82.6   82.9   83.1  ...   
906   76.2  76.2  76.2  76.2  76.4  76.7  77.0  77.5   78.2   79.2  ...   
716   69.7  69.7  69.8  69.8  72.0  71.3  72.4  75.7   75.4   77.2  ...   
1670  70.0  70.0  70.0  70.1  70.4  70.7  70.8  71.0   71.2   71.5  ...   
848   84.9  84.9  84.9  84.9  84.9  85.1  85.4  86.2   86.6   87.5  ...   
961   72.3  72.3  72.3  72.3  72.8  73.3  74.2  75.2   76.5   78.2  ...   
145   81.2  81.2  81.2  81.2  81.4  82.0  83.0  84.1   85.2   86.7  ...   
130   92.0  92.0  92.0  92.0  93.4  94.2  96.1  98.3  101.0  103.0  ...   

      col440  col441  col442  col443  col444  col445  col446  col447  col448  \
1062     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
236      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1097     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
906      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
716      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1670     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
848      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
961      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
145      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
130      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

      col449  
1062     0.0  
236      0.0  
1097     0.0  
906      0.0  
716      0.0  
1670     0.0  
848      0.0  
961      0.0  
145      0.0  
130      0.0  

[10 rows x 449 columns]

In [9]:
#預測
predicted=svm.predict(dataset_fortest)
predicted

array([5, 1, 5, 4, 4, 7, 4, 4, 3, 0], dtype=int64)

In [10]:
#實際的答案
expected=label.values
expected

array([5, 1, 5, 4, 4, 7, 4, 4, 1, 0], dtype=int64)

In [11]:
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected, predicted))
accuracy = accuracy_score(expected, predicted)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
print('precision:',metrics.precision_score(expected, predicted,average='macro')) 
print('recall:',metrics.recall_score(expected, predicted,average='macro'))
print('F1-score:',metrics.f1_score(label,predicted,average='macro'))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      0.50      0.67         2
           3       0.00      0.00      0.00         0
           4       1.00      1.00      1.00         4
           5       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         1

    accuracy                           0.90        10
   macro avg       0.83      0.75      0.78        10
weighted avg       1.00      0.90      0.93        10

[[1 0 0 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 1]]
Accuracy: 90.00%
precision: 0.8333333333333334
recall: 0.75
F1-score: 0.7777777777777777


D:\file\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\file\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\file\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\file\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning:

In [12]:
#import package
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn import ensemble, metrics
from sklearn.metrics import accuracy_score
from sklearn.utils import shuffle
import math

In [13]:
# 開啟 CSV 檔案
dataset= pd.read_csv('train.csv')
testset= pd.read_csv('test.csv')

In [14]:
#將dataset shuffle
dataset = shuffle(dataset)
label = dataset.label
dataset = dataset[dataset.columns[:449]]

隨機森林

In [15]:
#Random Forest
#引入library
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC

#10-fold cross-validation
kfold = KFold(10, True)
predicted = []
expected = []

#訓練模型
for train, test in kfold.split(dataset):
    X_train= dataset.iloc[train]
    Y_train = label.iloc[train]
    X_test = dataset.iloc[test]
    Y_test = label.iloc[test]
    forest = ensemble.RandomForestClassifier(n_estimators = 100)
    forest.fit(X_train,Y_train)
    expected.extend(Y_test)
    predicted.extend(forest.predict(X_test))

D:\file\anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass shuffle=True as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [16]:
print("Macro-average: {0}".format(metrics.f1_score(expected,predicted,average='macro')))
print("Micro-average: {0}".format(metrics.f1_score(expected,predicted,average='micro')))
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected, predicted))
accuracy = accuracy_score(expected, predicted)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

print("Average = macro")
print('precision:',metrics.precision_score(expected, predicted,average='macro')) 
print('recall:',metrics.recall_score(expected, predicted,average='macro'))
print('F1-score:',metrics.f1_score(expected, predicted,labels=[1,2,3,4],average='macro'))

print("\n")
print("Average = micro")
print('precision:', metrics.precision_score(expected, predicted, average='micro')) 
print('recall:',metrics.recall_score(expected, predicted,average='micro'))
print('F1-score:',metrics.f1_score(expected, predicted,labels=[1,2,3,4],average='micro'))

print("\n")
print("Average = weighted")
print('precision:', metrics.precision_score(expected, predicted, average='weighted'))
print('recall:',metrics.recall_score(expected, predicted,average='weighted'))
print('F1-score:',metrics.f1_score(expected,predicted,labels=[1,2,3,4],average='weighted'))

Macro-average: 0.9948337241537992
Micro-average: 0.9948305571510626
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       145
           1       1.00      0.99      0.99       207
           2       1.00      1.00      1.00       119
           3       0.99      1.00      1.00       238
           4       0.99      0.99      0.99       256
           5       0.99      1.00      1.00       264
           6       1.00      1.00      1.00       240
           7       1.00      1.00      1.00       272

    accuracy                           0.99      1741
   macro avg       1.00      0.99      0.99      1741
weighted avg       0.99      0.99      0.99      1741

[[142   0   0   0   2   1   0   0]
 [  0 205   0   2   0   0   0   0]
 [  0   0 119   0   0   0   0   0]
 [  0   0   0 238   0   0   0   0]
 [  0   1   0   0 254   0   0   1]
 [  0   0   0   0   0 264   0   0]
 [  0   0   0   0   0   1 239   0]
 [  0   0   0   0   0   0   1 271]]


In [17]:
#從訓練資料隨機抓幾筆出來做測試
from numpy import random

#確認訓練資料的筆數
dataset= pd.read_csv('train.csv')
print('資料的形式:{}'.format(dataset.shape))

#numpy.random.randint(low, high=None, size=None, dtype='l')
#隨機選出10筆
random.seed(1)
index_random=random.randint(1,1740,10)
print(index_random)

#從訓練資料取出這10筆資料
dataset_fortest = dataset.iloc[index_random]
label = dataset_fortest.label
dataset_fortest = dataset_fortest[dataset_fortest.columns[:449]]
dataset_fortest

資料的形式:(1741, 450)
[1062  236 1097  906  716 1670  848  961  145  130]


col1  col2  col3  col4  col5  col6  col7  col8   col9  col10  ...  \
1062  70.1  70.1  70.1  70.0  70.2  70.2  70.4  70.5   70.7   70.8  ...   
236   78.6  78.6  78.6  78.6  79.2  79.9  80.5  81.3   82.2   83.6  ...   
1097  81.4  81.4  81.4  81.5  81.8  82.0  82.3  82.6   82.9   83.1  ...   
906   76.2  76.2  76.2  76.2  76.4  76.7  77.0  77.5   78.2   79.2  ...   
716   69.7  69.7  69.8  69.8  72.0  71.3  72.4  75.7   75.4   77.2  ...   
1670  70.0  70.0  70.0  70.1  70.4  70.7  70.8  71.0   71.2   71.5  ...   
848   84.9  84.9  84.9  84.9  84.9  85.1  85.4  86.2   86.6   87.5  ...   
961   72.3  72.3  72.3  72.3  72.8  73.3  74.2  75.2   76.5   78.2  ...   
145   81.2  81.2  81.2  81.2  81.4  82.0  83.0  84.1   85.2   86.7  ...   
130   92.0  92.0  92.0  92.0  93.4  94.2  96.1  98.3  101.0  103.0  ...   

      col440  col441  col442  col443  col444  col445  col446  col447  col448  \
1062     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
236      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1097     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
906      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
716      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1670     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
848      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
961      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
145      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
130      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

      col449  
1062     0.0  
236      0.0  
1097     0.0  
906      0.0  
716      0.0  
1670     0.0  
848      0.0  
961      0.0  
145      0.0  
130      0.0  

[10 rows x 449 columns]

In [18]:
#預測
predicted=svm.predict(dataset_fortest)
predicted

array([5, 1, 5, 4, 4, 7, 4, 4, 3, 0], dtype=int64)

In [19]:
#實際的答案
expected=label.values
expected

array([5, 1, 5, 4, 4, 7, 4, 4, 1, 0], dtype=int64)

In [20]:
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected, predicted))
accuracy = accuracy_score(expected, predicted)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
print('precision:',metrics.precision_score(expected, predicted,average='macro')) 
print('recall:',metrics.recall_score(expected, predicted,average='macro'))
print('F1-score:',metrics.f1_score(label,predicted,average='macro'))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      0.50      0.67         2
           3       0.00      0.00      0.00         0
           4       1.00      1.00      1.00         4
           5       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         1

    accuracy                           0.90        10
   macro avg       0.83      0.75      0.78        10
weighted avg       1.00      0.90      0.93        10

[[1 0 0 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 1]]
Accuracy: 90.00%
precision: 0.8333333333333334
recall: 0.75
F1-score: 0.7777777777777777


D:\file\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\file\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\file\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\file\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: